[{"id":705818,"title":"Running setup.py bdist_wheel for cffi Failed building wheel for cryptography","body":"<p>I am trying to build a docker image. I have a install.sh file which will run when it is built. The contents of install.sh is as follows</p>\n\n<pre><code>sudo apt-get install -y python-dev python3.5 python3.5-dev\n# Install virtualenv\nsudo wget https://bootstrap.pypa.io/ez_setup.py -O /tmp/ez_setup.py\nsudo python3.5 /tmp/ez_setup.py\nsudo easy_install-3.5 pip\npip3.5 install virtualenv\n#pip install -U cffi\nvirtualenv -p python3.5 $HOME/venv/3.5\n# Install pip packages\n. $HOME/venv/3.5/bin/activate\npip install pyopenssl ndg-httpsclient pyasn1\npip install nose mock pytest coverage\nCFLAGS=\"-O0\" pip install lxml\ndeactivate\n</code></pre>\n\n<p>When <code>pip install pyopenssl ndg-httpsclient pyasn1</code> is executed, I recieve the following error</p>\n\n<pre><code>running install_egg_info\nCopying src/cryptography.egg-info to build/bdist.linux-x86_64/wheel/cryptography-1.1.1-py3.5.egg-info\nrunning install_scripts\nTraceback (most recent call last):\nFile \"&lt;string&gt;\", line 1, in &lt;module&gt;\nFile \"/tmp/pip-build-ytr1o8ux/cryptography/setup.py\", line 318, in &lt;module&gt;\n**keywords_with_side_effects(sys.argv)\nFile \"/usr/lib/python3.5/distutils/core.py\", line 148, in setup\ndist.run_commands()\nFile \"/usr/lib/python3.5/distutils/dist.py\", line 955, in run_commands\nself.run_command(cmd)\nFile \"/usr/lib/python3.5/distutils/dist.py\", line 974, in run_command\ncmd_obj.run()\nFile \"/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py\", line 213, in run\narchive_basename = self.get_archive_basename()\nFile \"/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py\", line 161, in get_archive_basename\nimpl_tag, abi_tag, plat_tag = self.get_tag()\nFile \"/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py\", line 155, in get_tag\nassert tag == supported_tags[0]\nAssertionError\n\n----------------------------------------\nRunning setup.py bdist_wheel for cffi\nFailed building wheel for cryptography\n</code></pre>\n\n<p>After looking at this <a href=\"https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3\" rel=\"nofollow\">link</a>, I tried to use updated wheels package </p>\n\n<pre><code>wget http://nipy.bic.berkeley.edu/scipy_installers/wheel-0.24.0-py2.py3-none-any.whl\npip install wheel-0.24.0-py2.py3-non-any.whl\n</code></pre>\n\n<p>Still the same error. Inspite of this error, the image is successfully built. Any help will be appreciated.</p>\n\n<p>Thanks in advance.</p>\n","related_questions":[{"id":676856,"title":"Cherrytree Fails to Run","body":"<p>When trying to run Cherrytree from terminal, I get the following errors:</p>\n\n<blockquote>\n  <p>&nbsp;>cherrytree<br/>\n  &nbsp;Traceback (most recent call last):<br/>\n  &nbsp;&nbsp;File \"/usr/bin/cherrytree\", line 65, in <br/>\n  &nbsp;&nbsp;&nbsp;&nbsp;f_main(args)<br/>\n  &nbsp;&nbsp;File \"/usr/bin/cherrytree\", line 46, in f_main<br/>\n  &nbsp;&nbsp;&nbsp;&nbsp;import main<br/>\n  &nbsp;&nbsp;File \"/usr/share/cherrytree/modules/main.py\", line 22, in <code>&lt;module&gt;</code><br/>\n  &nbsp;&nbsp;&nbsp;&nbsp;import gtk, gobject<br/>\n  &nbsp;ImportError: No module named gtk</p>\n</blockquote>\n\n<p>Trying to run it from Unity's sidebar simply fails.</p>\n\n<p>Updated system via Software Updater right before installing Cherrytree.</p>\n\n<p>Please let me know if any further info would help solve this.  Thanks!</p>\n"},{"id":630064,"title":"Quickly fails to package help pages","body":"<p>I have been working on making a program (jekyll-helper) using Quickly and a while ago I worked on adding some content to the default help pages. I tested out open the help pages in the program while running the program through the <code>quickly run</code> command, and the help pages worked fine.</p>\n\n<p>However, when I made a package for the program using the <code>quickly package</code> command, installed the package, and ran the installed version of the program the help pages would not work properly. Whenever I would open the help pages via the menu option <code>Help &gt; Contents</code>, the following error would pop up in place of the help pages:</p>\n\n<blockquote>\n  <p>Document Not Found</p>\n  \n  <p>The URI ‘ghelp:jekyll-helper’ does not point to a valid page.</p>\n</blockquote>\n\n<p>Unfortunately I do not know when the issue began, as I only realized that the issue existed when I ran the installed version of the program, which was a bit of time after I had finished working on the help pages.</p>\n\n<p>I did some Google searching and found a few similar issues that people had, however none of them had the same exact issue as I had.</p>\n\n<p>I found this question on Ask Ubuntu that seemed to be related, <a href=\"http://askubuntu.com/questions/161198/problems-compiling-with-quickly\">Problems compiling with Quickly</a>. That person had a similar issue, and they were able to get an error message related to the issue by running <code>quickly package --verbose --extras</code>. So I tried running that command and the package was able to build, however I got several error messages. I put up a copy of the terminal output here: <a href=\"http://pastie.org/10214514\" rel=\"nofollow\">http://pastie.org/10214514</a>.</p>\n\n<p>The person who wrote that issue figured out that it was caused by a new line being in the long description on the program. However, I checked my program's information in the <code>DistUtilsExtra.auto.setup</code> section of the <code>setup.py</code> file and there was no newline in the long description. Also their error message was somewhat different from the corresponding one I got. Thus the issue I am having did not likely have the same cause as the other person's issue.</p>\n\n<p>I also found this somewhat related issue, <a href=\"http://askubuntu.com/questions/265848/quickly-gives-warnings-on-packageing-not-recognizing-setup-py\">Quickly gives warnings on packageing, not recognizing setup.py~</a>, however that issue appears to be somewhat different from the issue I have been having. Also that issue was caused by automatic backup files created by Gedit, however I am using Atom to edit the source, which is not making such backup files.</p>\n\n<p>The source code of the program is here: <a href=\"https://github.com/ExcaliburZero/jekyll-helper\" rel=\"nofollow\">https://github.com/ExcaliburZero/jekyll-helper</a></p>\n\n<p>How can this problem be fixed, and what is causing it?</p>\n"},{"id":531930,"title":"PPA build fails due to Python.h missing","body":"<p>I'm trying to package my application for Ubuntu using PPA. The build fails because it can't find <code>Python.h</code> (<a href=\"https://launchpadlibrarian.net/186457508/buildlog_ubuntu-utopic-i386.python-pyblock_0.52-3_FAILEDTOBUILD.txt.gz\" rel=\"nofollow\">build log here</a>). This library is provided by <code>libpython2.7-dev</code> and I have it in build dependencies and according to build log it is installed.</p>\n\n<p>Building using <code>dpkg-buildpackage</code> (or just simple installation using <code>make</code> and <code>make install</code>) works on my current Ubuntu 14.10 clean installation.</p>\n"},{"id":388359,"title":"Running python3.3 using virtulenv","body":"<p>I am using Ubuntu server 12.04. The default python version is 2.7. I have installed python 3.3 in /opt directory. When I try to create a virtualenv to use python 3.3, I get the following error:</p>\n\n<p>$virtualenv -p /opt/python3.3/bin/python3 python3_env</p>\n\n<p>Running virtualenv with interpreter /opt/python3.3/bin/python3\nTraceback (most recent call last):\n  File \"usr/lib/python2.7/dist-packages/virtualenv.py\", line 17, in  import zlib\nImportError: No module named 'zlib'</p>\n\n<p>How do I resolve this?</p>\n"},{"id":373207,"title":"Installing both lxml 3.1.2 and lxml2 on ubuntu 12.04","body":"<p>I asked this on SO: <a href=\"http://stackoverflow.com/questions/19852911/lxml-3-1-2-and-lxml2-both-on-ubuntu/19856674#19856674\">http://stackoverflow.com/questions/19852911/lxml-3-1-2-and-lxml2-both-on-ubuntu/19856674#19856674</a></p>\n\n<p>But it is perhaps more appropriate for AskUbuntu. So here it is again, reformulated.</p>\n\n<p>On the lxml site they suggest that it is possible to have both lxml2 and the newest version of lxml on ubuntu:</p>\n\n<blockquote>\n  <p>Using lxml with python-libxml2</p>\n  \n  <p>If you want to use lxml together with the official libxml2 Python\n  bindings (maybe because one of your dependencies uses it), you must\n  build lxml statically. Otherwise, the two packages will interfere in\n  places where the libxml2 library requires global configuration, which\n  can have any kind of effect from disappearing functionality to crashes\n  in either of the two. To get a static build, either pass the\n  --static-deps option to the setup.py script, or run pip with the STATIC_DEPS or STATICBUILD environment variable set to true, i.e.\n  STATIC_DEPS=true pip install lxml The STATICBUILD environment variable\n  is handled equivalently to the STATIC_DEPS variable, but is used by\n  some other extension packages, too.</p>\n</blockquote>\n\n<p>I am generally confused about how pip packages and ubuntu packages get along, so I hesitate to run <i>STATIC_DEPS=true pip install lxml</i>. Will it damage/confuse my installed lxml2 package? </p>\n\n<p>The suggestion on SO was to install the new lxml in a virtualenv. That looks like the best way to go, but the lxml site is suggesting that a dual installation will work also. </p>\n\n<p>In general: what happens if I use pip (to get a newer install) for a package that is already installed by apt-get? </p>\n"},{"id":321483,"title":"Problem with installing a python module","body":"<p>Hi I am unable to download a python module dm.smlsec.binding 1.0b3. The following error is what I get. I have attached my log file please help me sorting out</p>\n\n<hr>\n\n<p>/usr/local/bin/pip run on Thu Jul 18 12:23:36 2013\nDownloading/unpacking dm.xmlsec.binding</p>\n\n<p>Running setup.py egg_info for package dm.xmlsec.binding</p>\n\n<pre><code>Traceback (most recent call last):\n\n  File \"&lt;string&gt;\", line 16, in &lt;module&gt;\n\n  File \"/tmp/pip-build-student/dm.xmlsec.binding/setup.py\", line 199, in &lt;module&gt;\n\n    **setupArgs\n\n  File \"/usr/lib/python2.7/distutils/core.py\", line 112, in setup\n\n    _setup_distribution = dist = klass(attrs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py\", line 260, in __init__\n\n  File \"/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py\", line 284, in fetch_build_eggs\n\n  File \"/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py\", line 569, in resolve\n\n    dist = best.get(req.key)\n\npkg_resources.VersionConflict: (lxml 2.3.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('lxml&gt;=3.0'))\n\nComplete output from command python setup.py egg_info:\n\nTraceback (most recent call last):\n</code></pre>\n\n<p>File \"\", line 16, in </p>\n\n<p>File \"/tmp/pip-build-student/dm.xmlsec.binding/setup.py\", line 199, in </p>\n\n<pre><code>**setupArgs\n</code></pre>\n\n<p>File \"/usr/lib/python2.7/distutils/core.py\", line 112, in setup</p>\n\n<pre><code>_setup_distribution = dist = klass(attrs)\n</code></pre>\n\n<p>File \"/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py\", line 260, in <strong>init</strong></p>\n\n<p>File \"/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py\", line 284, in fetch_build_eggs</p>\n\n<p>File \"/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py\", line 569, in resolve</p>\n\n<pre><code>dist = best.get(req.key)\n</code></pre>\n\n<p>pkg_resources.VersionConflict: (lxml 2.3.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('lxml>=3.0'))</p>\n\n<hr>\n\n<p>Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-student/dm.xmlsec.binding</p>\n\n<p>Exception information:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py\", line 139, in main\n    status = self.run(options, args)\n  File \"/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py\", line 266, in run\n    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)\n  File \"/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg/pip/req.py\", line 1057, in prepare_files\n    req_to_install.run_egg_info()\n  File \"/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg/pip/req.py\", line 236, in run_egg_info\n    command_desc='python setup.py egg_info')\n  File \"/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg/pip/util.py\", line 662, in call_subprocess\n    % (command_desc, proc.returncode, cwd))\nInstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-student/dm.xmlsec.binding</p>\n"},{"id":317606,"title":"Cpyrit-cuda build install problem","body":"<p>I'm getting an error when I try to build <code>cpyrit-cuda</code> on Ubuntu 12.04 LTS here is what I'm getting:</p>\n\n<pre><code>brandon@San-Fran-La-49:~/cpyrit-cuda-0.4.0$ sudo python setup.py build\nrunning build\nrunning build_ext\nSkipping rebuild of Nvidia CUDA kernel ...\nBuilding modules...\nbuilding 'cpyrit._cpyrit_cuda' extension\ngcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _cpyrit_cuda.c -o build/temp.linux-x86_64-2.7/_cpyrit_cuda.o -Wall -fno-strict-aliasing -DVERSION=\"0.4.0\"\ngcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/_cpyrit_cuda.o -lcrypto -lcuda -lz -o build/lib.linux-x86_64-2.7/cpyrit/_cpyrit_cuda.so\n/usr/bin/ld: cannot find -lcuda\ncollect2: ld returned 1 exit status\nerror: command 'gcc' failed with exit status 1\n</code></pre>\n\n<p>All help is greatly appreciated, thanks!</p>\n"},{"id":155841,"title":"How to build PyQt for Deadsnakes Python 2.7 on Ubuntu 10.04?","body":"<p>I am trying to configure Python2.7 on Ubuntu 10.04 as an alternative package.</p>\n\n<p>I got the Deadsnakes PPA</p>\n\n<p>I set up pip and virtualenv</p>\n\n<p>Now, I am trying to build PyQt (PySide seems to have similar problems in that pip is not supported)</p>\n\n<p>I have activated virtualenv and have downloaded SIP.</p>\n\n<pre><code>(qtenv)~/sip-4.13.3$ python2.7 configure.py\n\n(qtenv)~/sip-4.13.3$ make\n\ngcc -c -pipe -fPIC -O2 -w -DNDEBUG -I. -I/usr/include/python2.7 -o siplib.o siplib.c\nsiplib.c:20:20: error: Python.h: No such file or directory\n</code></pre>\n\n<p>and of course now there is a cornucopia of errors after that</p>\n\n<p>Supposedly, I would need python-dev for the Python headers but I already have it installed in regular enviroment(python 2.6 on Ubuntu 10.04). </p>\n\n<p>So how do I get the headers file for python2.7 builds?</p>\n\n<p>It seems I am only a few steps away from shaving the yak...</p>\n\n<hr>\n\n<p>For other readers, a synopsis...</p>\n\n<p>The OP is running Ubuntu 10.4 (which by default uses an older version of Python2.6) but wants Python2.7 and the PyQt package, which depends on the SIP package (from the authors of PyQt.)</p>\n\n<p>The OP has installed and is using virtualenv, which lets you have multiple versions of Python installed.</p>\n\n<p>PyQt is a binding from Python to the Qt C library. Its installation requires compilation against the Python header files (e.g. Python.h which is found e.g. in /usr/local/include/python2.6, or ...2.7)</p>\n\n<p>A standard installation of Ubuntu does not have those Python header files. They can be installed as package python-dev, but they will match the installed version of Python e.g. 2.6.</p>\n\n<p>Evidently the OP has installed python-dev for Python2.6 (and the virtualenv can see it). The OP changed directory to the SIP directory and ran the configure script, but since it was executed by Python2.7, it configured the make scripts for SIP to look for Python2.7 header files. The OP needs to install python-dev package for Python2.7 into their second, virtual, Python environment that is running Python2.7.</p>\n\n<p>(I am also trying to build SIP and PyQt on Ubuntu 12.04 and it is also failing to find /usr/local/include/Python.h. I installed python-dev which installed to /usr/include/python2.7. Maybe the configure script for PyQt is flawed. This is a common problem on Linux, that there is no absolutely standard place to install things, especially when multiple versions of a thing might be installed.)</p>\n"},{"id":286755,"title":"installing ecdsa","body":"<p>how do i install ecdsa? im getting this error</p>\n\n<pre>\nubuntu@ubuntu:~$ electrum\nError: python-ecdsa does not seem to be installed. Try 'sudo pip install ecdsa'\nubuntu@ubuntu:~$ sudo pip install ecdsa\nDownloading/unpacking ecdsa\n  Running setup.py egg_info for package ecdsa\n    Traceback (most recent call last):\n      File \"\", line 3, in \n    ImportError: No module named setuptools.command\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n\n  File \"\", line 3, in \n\nImportError: No module named setuptools.command\n</pre>\n\n<hr>\n\n<pre>\nCommand python setup.py egg_info failed with error code 1\nStoring complete log in ./pip-log.txt\nubuntu@ubuntu:~$ </pre>\n"},{"id":171307,"title":"Error while making a .deb package with Quickly: setup.py install_egg_info failed","body":"<p>I wrote a little program and now I trying to make a <code>.deb</code> package out of it.\nWhen I run <code>quickly --verbose package</code> I get this:</p>\n\n<pre><code>quickly --verbose package \n/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed\n  import gobject._gobject\n/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:40: Warning: specified class size for type `PyGtkGenericCellRenderer' is smaller than the parent type's `GtkCellRenderer' class size\n  from gtk import _gtk\n/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_get_qdata: assertion `node != NULL' failed\n  from gtk import _gtk\nsetup.py install_egg_info failed\nAn error has occurred when creating debian packaging\nERROR: can't create or update ubuntu package\nERROR: package command failed\nAborting\n</code></pre>\n\n<p>I read <a href=\"https://answers.launchpad.net/quickly/+question/192700\" rel=\"nofollow\">Jono Bacon's question on the Quickly developer website</a> and he had exactly the same problem as I have, but even though he explained how to fix it I don't understand what I'm supposed to do. I'm new to Quickly and to Python too. What do I need to do?</p>\n"}]}]