[{"id":715801,"title":"gnome-builder crashes when trying to open project","body":"<p>When I try to open a project in <code>gnome-builder</code>, whether it's by clicking one of the projects on this screen it starts up on (I have put a big black box over some more private stuff):</p>\n\n<p><a href=\"https://i.stack.imgur.com/awrQs.png\" rel=\"nofollow\"><img src=\"https://i.stack.imgur.com/awrQs.png\" alt=\"&quot;Select a Project&quot; screen in &lt;code&gt;gnome-builder&lt;/code&gt;\"></a></p>\n\n<p>Or if I use the <code>New</code> button and select an already existing project, it just closes. And over the course of the time that I started the application I have been getting these errors in Terminal:</p>\n\n<pre><code>22:14:57.0356                         libpeas[13410]:  WARNING: Error importing plugin 'html_preview_plugin':\nTraceback (most recent call last):\n  File \"/usr/lib/python3.4/importlib/__init__.py\", line 109, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2254, in _gcd_import\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2237, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2226, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1200, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1129, in _exec\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1471, in exec_module\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 321, in _call_with_frames_removed\n  File \"/usr/lib/x86_64-linux-gnu/gnome-builder/plugins/html_preview_plugin/__init__.py\", line 31, in &lt;module&gt;\n    from gi.repository import Builder\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2237, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2226, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1191, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1161, in _load_backward_compatible\n  File \"/usr/lib/python3/dist-packages/gi/importer.py\", line 114, in load_module\n    introspection_module = get_introspection_module(namespace)\n  File \"/usr/lib/python3/dist-packages/gi/module.py\", line 271, in get_introspection_module\n    module = IntrospectionModule(namespace, version)\n  File \"/usr/lib/python3/dist-packages/gi/module.py\", line 120, in __init__\n    repository.require(namespace, version)\ngi.RepositoryError: Typelib file for namespace 'Ggit', version '1.0' not found\n22:14:57.0356                         libpeas[13410]:  WARNING: Error loading plugin 'html_preview_plugin'\n22:14:57.0481                         libpeas[13410]:  WARNING: Error importing plugin 'jedi_plugin':\nTraceback (most recent call last):\n  File \"/usr/lib/python3.4/importlib/__init__.py\", line 109, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2254, in _gcd_import\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2237, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2226, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1200, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1129, in _exec\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1471, in exec_module\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 321, in _call_with_frames_removed\n  File \"/usr/lib/x86_64-linux-gnu/gnome-builder/plugins/jedi_plugin.py\", line 34, in &lt;module&gt;\n    from gi.repository import Ide\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2237, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2226, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1191, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1161, in _load_backward_compatible\n  File \"/usr/lib/python3/dist-packages/gi/importer.py\", line 114, in load_module\n    introspection_module = get_introspection_module(namespace)\n  File \"/usr/lib/python3/dist-packages/gi/module.py\", line 271, in get_introspection_module\n    module = IntrospectionModule(namespace, version)\n  File \"/usr/lib/python3/dist-packages/gi/module.py\", line 120, in __init__\n    repository.require(namespace, version)\ngi.RepositoryError: Typelib file for namespace 'Ggit', version '1.0' not found\n22:14:57.0481                         libpeas[13410]:  WARNING: Error loading plugin 'jedi_plugin'\n22:14:57.0490                         libpeas[13410]:  WARNING: Error importing plugin 'python_gi_imports_completion':\nTraceback (most recent call last):\n  File \"/usr/lib/python3.4/importlib/__init__.py\", line 109, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2254, in _gcd_import\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2237, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2226, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1200, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1129, in _exec\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1471, in exec_module\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 321, in _call_with_frames_removed\n  File \"/usr/lib/x86_64-linux-gnu/gnome-builder/plugins/python_gi_imports_completion.py\", line 36, in &lt;module&gt;\n    from gi.repository import Ide\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2237, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 2226, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1191, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 1161, in _load_backward_compatible\n  File \"/usr/lib/python3/dist-packages/gi/importer.py\", line 114, in load_module\n    introspection_module = get_introspection_module(namespace)\n  File \"/usr/lib/python3/dist-packages/gi/module.py\", line 271, in get_introspection_module\n    module = IntrospectionModule(namespace, version)\n  File \"/usr/lib/python3/dist-packages/gi/module.py\", line 120, in __init__\n    repository.require(namespace, version)\ngi.RepositoryError: Typelib file for namespace 'Ggit', version '1.0' not found\n22:14:57.0490                         libpeas[13410]:  WARNING: Error loading plugin 'python_gi_imports_completion'\n</code></pre>\n\n<p>And when I ask it to open a project it exists with this final error message:</p>\n\n<pre><code>22:15:39.0312               gb-greeter-window[13410]:  WARNING: Typelib file for namespace 'Ggit', version '1.0' not found\n</code></pre>\n\n<p>So am I just doing something wrong or is this a bug which I should report?</p>\n\n<hr>\n\n<p><strong>OS Information:</strong></p>\n\n<pre><code>No LSB modules are available.\nDistributor ID: Ubuntu\nDescription:    Ubuntu 15.10\nRelease:    15.10\nCodename:   wily\nFlavour: GNOME\nGNOME Version: 3.18\n</code></pre>\n\n<p><strong>Package Information:</strong></p>\n\n<pre><code>gnome-builder:\n  Installed: 3.18.0-0ubuntu1~wily4\n  Candidate: 3.18.0-0ubuntu1~wily4\n  Version table:\n *** 3.18.0-0ubuntu1~wily4 0\n        500 http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu/ wily/main amd64 Packages\n        100 /var/lib/dpkg/status\n</code></pre>\n","related_questions":[{"id":642027,"title":"Google Earth crashes when opened","body":"<p>I recently downloaded the Google Earth <code>.deb</code> file for 64-bit <a href=\"http://www.google.co.uk/intl/en-GB/earth/download/ge/agree.html\" rel=\"nofollow\">from here</a>. And I installed it with:</p>\n\n<pre><code>sudo dpkg -i google-earth-stable_current_amd64.deb\n</code></pre>\n\n<p>And I of course also installed all of the other necessary dependencies with:</p>\n\n<pre><code>sudo apt-get install -f\n</code></pre>\n\n<p>Which Google Earth depends on. But now when I start Google Earth with:</p>\n\n<pre><code>google-earth\n</code></pre>\n\n<p>It launches, stays open for about 10 seconds, and then exits. From opening it to it closing this is what I see in Terminal:</p>\n\n<pre><code>[0628/171243:ERROR:net_util.cc(2195)] Not implemented reached in bool net::HaveOnlyLoopbackAddresses()\n[0628/171244:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171244:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171244:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171244:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/161245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/161245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171245:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171246:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171247:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171247:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171247:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171247:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171247:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171249:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171249:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171249:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171249:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171250:WARNING:backend_impl.cc(1875)] Destroying invalid entry.\n[0628/171253:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171253:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171253:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171253:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n[0628/171254:ERROR:nss_ocsp.cc(581)] No URLRequestContext for OCSP handler.\n\n\nAnother crash happened while handling crash!\n</code></pre>\n\n<p>I am not sure of the meaning of these error messages, and what I should do about them to stop it from only lasting 10 seconds. So is there anyway I can fix this? Or is this some sort of bug? If so, where should I report it?</p>\n\n<hr>\n\n<p><strong>OS Information:</strong></p>\n\n<pre><code>Description:    Ubuntu 15.04\nRelease:    15.04\n</code></pre>\n\n<p><strong>Package Information:</strong></p>\n\n<pre><code>google-earth-stable:\n  Installed: 7.1.4.1529-r0\n  Candidate: 7.1.4.1529-r0\n  Version table:\n *** 7.1.4.1529-r0 0\n        100 /var/lib/dpkg/status\n</code></pre>\n"},{"id":685568,"title":"XBMC, caused 15.04 gnome to crash and corrupt boot up","body":"<p>I was running 15.04 velvet with Gnome, when I installed XBMC and attempted to load my video library Ubuntu crashed which somehow corrupted the boot sequence and give a\" 1.574824] ACPI PCC probe failed., starting version 219, failed command:READ DMA, ata1.00: { DRDY ERR}, etc..... error\" There are a number of lines with various errors associated as well. I tried to reinstall but the install hangs half way through. I was able to run from USB and look at the drive with GPART, and the drive seems okay. I tried repairing the primary HD, to no avail. What can I do?</p>\n"},{"id":672290,"title":"OBS crashes when I try to launch it","body":"<p>I have installed OBS Studio in 14.04and then to 15.04 and when I open it I get this message </p>\n\n<pre><code>Attempted path: share/obs/obs-studio/locale/en-US.ini\nAttempted path: /usr/share/obs/obs-studio/locale/en-US.ini\nAttempted path: share/obs/obs-studio/locale.ini\nAttempted path: /usr/share/obs/obs-studio/locale.ini\nAttempted path: share/obs/obs-studio/themes/Default.qss\nAttempted path: /usr/share/obs/obs-studio/themes/Default.qss\nAttempted path: share/obs/obs-studio/license/gplv2.txt\nAttempted path: /usr/share/obs/obs-studio/license/gplv2.txt\ninfo: OBS 0.11.2 (linux)\ninfo: ---------------------------------\ninfo: Processor: 2 logical cores\ninfo: Processor: AMD Athlon(tm) 64 X2 Dual Core Processor 4000+\ninfo: Physical Memory: 2000MB Total\ninfo: Kernel Version: Linux 3.16.0-48-generic\ninfo: Distribution: \"Ubuntu\" \"14.04\"\ninfo: ---------------------------------\ninfo: audio settings reset:\n    samples per sec: 44100\n    speakers:        2\n    buffering (ms):  1000\ninfo: X and Y: 902 489\nBackbuffers: 2\nColor Format: 3\nZStencil Format: 0\nAdapter: 0\n\nerror: Failed to create OpenGL context.\nerror: Failed to create context!\n*** Error in `obs': double free or corruption (out): 0x00000000029010c0 ***\nAborted (core dumped)\n</code></pre>\n\n<p>I have reinstalled with no luck. Can anyone help?</p>\n"},{"id":664729,"title":"Gnome is being incredibly unstable and applications are frequently crashing","body":"<p>I don't know how this happened, after I updated my software everything on Gnome started breaking. This is what I have noticed so far:</p>\n\n<ul>\n<li>The terminal crashes when I click on the menu items</li>\n<li>The <code>Screenshot</code> application crashes when I try to save a screenshot</li>\n<li>The <code>Clocks</code> application crashes when I try to add a new clock</li>\n</ul>\n\n<p>The terminal also looks weird, it used to be white. This must be due to missing files or something: (I couldn't crop it because <code>Shotwell Viewer</code> kept crashing</p>\n\n<p><a href=\"http://i.stack.imgur.com/1H3bq.png\" rel=\"nofollow\"><img src=\"http://i.stack.imgur.com/1H3bq.png\" alt=\"enter image description here\"></a></p>\n\n<p>I assume that I must be missing files or something, but when I do <code>sudo apt-get update</code>, <code>sudo apt-get upgrade</code> or <code>sudo apt-get dist-upgrade</code> nothing happens.</p>\n\n<p>I'm running 3.12.2 on Ubuntu 14.04 LTS.</p>\n\n<p>It's only getting worse, and I believe it occured after trying to upgrade to Gnome 3.14. How can I fix this?</p>\n"},{"id":660051,"title":"Ubuntu 14.04 crashes when running a project in Netbeans 8.0.2","body":"<p>There is one more topic with similar question, however all the suggested solutions there, didn't work for me.</p>\n\n<p>I'm using Netbeans 8.0.2.\nWhen I try to run a project, the whole system crashes.</p>\n\n<pre><code>dpkg --list | grep -i jdk\n</code></pre>\n\n<p>gives</p>\n\n<pre><code>ii  default-jdk                                           2:1.7-51                                            amd64        Standard Java or Java compatible Development Kit\nii  default-jdk-doc                                       0.51                                                all          Standard Java or Java compatible Development Kit (documentation)\nii  openjdk-7-doc                                         7u79-2.5.6-0ubuntu1.14.04.1                         all          OpenJDK Development Kit (JDK) documentation\nii  openjdk-7-jdk:amd64                                   7u79-2.5.5-0ubuntu0.14.04.2                         amd64        OpenJDK Development Kit (JDK)\nii  openjdk-7-jre:amd64                                   7u79-2.5.5-0ubuntu0.14.04.2                         amd64        OpenJDK Java runtime, using Hotspot JIT\nii  openjdk-7-jre-headless:amd64                          7u79-2.5.5-0ubuntu0.14.04.2                         amd64        OpenJDK Java runtime, using Hotspot JIT (headless)\nii  oracle-java8-installer                                8u51+8u51arm-1~webupd8~0                            all          Oracle Java(TM) Development Kit (JDK) 8\n</code></pre>\n\n<p>Any suggestions are welcome. </p>\n"},{"id":655812,"title":"The Ubuntu Software Center is crashing and also the updater","body":"<p>Lately everytime that i start up my laptop, it says that ubuntu has experienced an internal error. Then when I tried to open the Ubuntu Software Center it crashes every time. The same things happens when i try to open the software updater. I'm not very good at troubleshooting so I appreciate any help that I can get.</p>\n\n<p>Update: After running what you said David, this is what came up in the terminal.\nsoftwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'\n2015-08-04 22:20:23,607 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'\n2015-08-04 22:20:24,354 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file\n2015-08-04 22:20:24,387 - softwarecenter.plugin - INFO - activating plugin ''\n2015-08-04 22:20:24,565 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()\n2015-08-04 22:20:26,213 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)\n2015-08-04 22:20:26,226 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed\nTraceback (most recent call last):\n  File \"/usr/share/software-center/softwarecenter/backend/reviews/<strong>init</strong>.py\", line 358, in _save_review_stats_cache_blocking\n    self._dump_bsddbm_for_unity(outfile, outdir)\n  File \"/usr/share/software-center/softwarecenter/backend/reviews/<strong>init</strong>.py\", line 377, in _dump_bsddbm_for_unity\n    0600)\nDBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')\n/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 76 was not found when attempting to remove it\n  return super(MainContext, self).iteration(may_block)\nTraceback (most recent call last):\n  File \"/usr/share/software-center/softwarecenter/db/pkginfo_impl/aptcache.py\", line 261, in open\n    self._cache = apt.Cache(progress)\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 107, in <strong>init</strong>\n    self.open(progress)\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 151, in open\n    self._cache = apt_pkg.Cache(progress)\nSystemError: E:Encountered a section with no Package: header, E:Problem with MergeList /var/lib/apt/lists/repo.steampowered.com_steam_dists_precise_steam_i18n_Translation-en, E:The package lists or status file could not be parsed or opened.\n2015-08-04 22:20:33,546 - softwarecenter.db.enquire - ERROR - _get_estimate_nr_apps_and_nr_pkgs failed\nTraceback (most recent call last):\n  File \"/usr/share/software-center/softwarecenter/db/enquire.py\", line 115, in _get_estimate_nr_apps_and_nr_pkgs\n    tmp_matches = enquire.get_mset(0, len(self.db), None, xfilter)\n  File \"/usr/share/software-center/softwarecenter/db/appfilter.py\", line 89, in <strong>call</strong>\n    if (not pkgname in self.cache and\n  File \"/usr/share/software-center/softwarecenter/db/pkginfo_impl/aptcache.py\", line 281, in <strong>contains</strong>\n    return self._cache.<strong>contains</strong>(k)\nAttributeError: 'NoneType' object has no attribute '<strong>contains</strong>'\nTraceback (most recent call last):\n  File \"/usr/bin/software-center\", line 183, in \n    app.run(args)\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/app.py\", line 1378, in run\n    self.show_available_packages(args)\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/app.py\", line 1316, in show_available_packages\n    self.view_manager.set_active_view(ViewPages.AVAILABLE)\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/session/viewmanager.py\", line 150, in set_active_view\n    view_widget.init_view()\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/panes/availablepane.py\", line 227, in init_view\n    self.cache, self.db, self.icons, self.apps_filter)\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/views/lobbyview.py\", line 80, in <strong>init</strong>\n    self.build()\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/views/lobbyview.py\", line 326, in build\n    self._build_homepage_view()\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/views/lobbyview.py\", line 121, in _build_homepage_view\n    self._append_whats_new()\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/views/lobbyview.py\", line 255, in _append_whats_new\n    whats_new_cat = self._update_whats_new_content()\n  File \"/usr/share/software-center/softwarecenter/ui/gtk3/views/lobbyview.py\", line 240, in _update_whats_new_content\n    docs = whats_new_cat.get_documents(self.db)\n  File \"/usr/share/software-center/softwarecenter/db/categories.py\", line 131, in get_documents\n    nonblocking_load=False)\n  File \"/usr/share/software-center/softwarecenter/db/enquire.py\", line 330, in set_query\n    self._blocking_perform_search()\n  File \"/usr/share/software-center/softwarecenter/db/enquire.py\", line 225, in _blocking_perform_search\n    matches = enquire.get_mset(0, self.limit, None, xfilter)\n  File \"/usr/share/software-center/softwarecenter/db/appfilter.py\", line 89, in <strong>call</strong>\n    if (not pkgname in self.cache and\n  File \"/usr/share/software-center/softwarecenter/db/pkginfo_impl/aptcache.py\", line 281, in <strong>contains</strong>\n    return self._cache.<strong>contains</strong>(k)\nAttributeError: 'NoneType' object has no attribute '<strong>contains</strong>'\nalejandro@ToshibaLaptop:~$ Traceback (most recent call last):\n  File \"/usr/share/software-center/update-software-center-agent\", line 81, in \n    cache = apt.Cache(memonly=True)\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 107, in <strong>init</strong>\n    self.open(progress)\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 151, in open\n    self._cache = apt_pkg.Cache(progress)\nSystemError: E:Encountered a section with no Package: header, E:Problem with MergeList /var/lib/apt/lists/repo.steampowered.com_steam_dists_precise_steam_i18n_Translation-en, E:The package lists or status file could not be parsed or opened.</p>\n"},{"id":588301,"title":"What to do when Ubuntu crashes upon opening new session?","body":"<p>Trying to install Gnome D/E, and when I log out of Unity in Ubuntu 14.10 and try to log back in, all I see is my desktop background, and nothing else comes up, until the computer reboots. I have uninstalled everything that came with the Gnome meta-package and made sure the only installed display monitor is lightdm, which is the stock. What can I do to stop this crash in every new session? I'm no longer interested in installing Gnome D/E.</p>\n\n<p>I'm new-ish to the Linux world, sorry if I end up asking too many follow-up questions.</p>\n"},{"id":581009,"title":"Problem when opening /proc file","body":"<p>My laptop came with Windows 7 but it now dual boots with Xubuntu 14.04.\nJust out of interest I tried to open the /proc file a week or so ago. I say tried because the file did not open but the keyboard and mouse froze. I had to switch off and on to get up and running again. In case it was a one off glitch I tried the same thing again and again with the same result.\nI am rather concerned that there may be an important problem here that may start to impinge on the general running of the OS. \nHas anyone seen this happen before and found a cure?</p>\n"},{"id":571245,"title":"Gnome crashing on Ubuntu 14.04 - How can I fix or helping fix it?","body":"<p>I've installed Ubuntu 14.04 on my Lenovo ThinkPad. I checked the option to encrypt the disk during the installation (I don't think that this has an impact on Gnome, but you never know).</p>\n\n<p>As I mentioned in the title, Gnome is crashing often, meaning the Monitor just freezes, while background tasks like playing music continues. When Gnome freezes, I can switch to the CLI version (Ctrl+Alt+F1) and back. The freeze occurs sometimes when the laptop is running on the battery but also when the power is plugged. Also I can't figure a pattern of the programs (sometimes when only Firefox is running, sometimes when only Spotify is running, sometimes when VirtualBox and NetBeans are running), so I guess it's not a problem related to one particular program. It's basically as described here: <a href=\"http://askubuntu.com/questions/455301/how-to-restart-gnome-shell-after-it-became-unresponsive-freeze\">How to restart Gnome-shell, after it became unresponsive/freeze?</a></p>\n\n<p>So why a new question? Because that's not all. I also have trouble when I try to use the internal monitor of my laptop and an external, as additional monitor. I made a thread about that one week ago, but haven't received any feedback since: <a href=\"http://askubuntu.com/questions/566975/ubuntu-on-laptop-external-monitor-not-working-properly\">Ubuntu on Laptop external monitor not working properly</a>\n<strong><em>Edit: That one's fixed.</em></strong></p>\n\n<p>And then there's a third thing. Sometimes, not always, when I shut down my computer it get stuck at the Ubuntu screen with the loading animation. The fan is still running, the computer is generating some heat and the monitor is on, but it doesn't seam to do anything (I let it run over night once, but nothing happened). Other times it just powers off normally.</p>\n\n<p>The fourth thing I'm worried about is the heat. My laptop get's a lot hotter then when it used to run windows. But I guess, that's not Gnome related (so kind of a bonus question ;))</p>\n\n<p>I guess the freez, external monitor and shut down are somehow connected to Gnome, please correct me if I'm wrong. Question: What can I do to fix it? Is there some kind of log, that I could send to the gnome developers (or a debug mode I could enable to get the log)? Is it a Gnome problem or something else?</p>\n"},{"id":530816,"title":"Gnome 3.4.2 image viewer crashes system","body":"<p>In my 12.04 system when I try to open a jpeg file on a thumb drive ( which may have been written by Windows) the system freezes completely and must be turned off to regain control. The failure mode: The image viewer displays its screen but the image area is black (empty). There does not seem to be a problem for screen captures or images on my hard drives. The thumb drive contains images that I created and saved so the images are not likely to contain any viruses. If no one has a solution please at least tell me how to disable the viewer while I get a replacement viewer.\nThanks in advance.</p>\n"}]}]